### ISSUE TITLE
按钮背景色充满特效

### ISSUE THREAD

**Issue by ChrisLuckComes** [ChrisLuckComes/myblog#10]
```CSS
    button {
      width: 120px;
      height: 40px;
      background: transparent;
      border: 1px solid black;
      border-radius: 2px;
    }

    .btn {
      border-radius: 2px;
      background: #00D4D3;
      width: 0;
      height: 100%;
      transition-property: width;
      transition-duration: 0.25s;
      transition-timing-function: linear;
      transition-delay: 0s;
    }

    .btn:hover {
      width: 120px
    }
```
```HTML
  <div class="btn">
    <button>click</button>
  </div>
```
[戳此预览](https://jsfiddle.net/xoph8qa7/)
