### ISSUE TITLE
样式名很麻烦？使用postcss-alias偷懒

### ISSUE THREAD

**Issue by ChrisLuckComes** [ChrisLuckComes/myblog#24]
github:[postcss-alias](https://github.com/seaneking/postcss-alias)

使用此插件 可以定义别名
```CSS
@alias{
 ft:font-size
}
```
其他地方用ft就可以了
