### ISSUE TITLE
字体颜色渐变

### ISSUE THREAD

**Issue by ChrisLuckComes** [ChrisLuckComes/myblog#26]
思路：先设置背景色渐变——规定背景的划分区域——保险一点再设置（text-fill- color会覆盖color所定义的字体颜色）

/* 这个文字效果只在webkit内核的浏览器上才能正常工作。Firefox 浏览器不支持在文字上使用background-clip属性 */
```css
h1.start-gradient {
  font-weight: bold;
  font-family: helvetica;
  text-align:center;
  background: -webkit-linear-gradient(left, #4f185d , #fe5d4b);     /* 背景色渐变 */
  -webkit-background-clip: text;         /* 规定背景的划分区域 */
  -webkit-text-fill-color: transparent;  /* 防止字体颜色覆盖 */
}
```
```HTML
<h1 class="start-gradient">快速开始</h1>
```
